### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#101]
Fix compiler warnings, many of which were introduced with an incomplete change to support interfaces.

**To Reproduce**
1. Build from a clean configuration.

Results:

/Users/mcoblenz/code/Obsidian/src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
Warning:(1213, 15) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
        field.typ match {
Warning:(1538, 9) match may not be exhaustive.
It would fail on the following input: OwnershipTransfer(_)
        e match {
/Users/mcoblenz/code/Obsidian/src/main/scala/edu/cmu/cs/obsidian/protobuf/ProtobufGen.scala
Warning:(88, 11) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
        f.typ match {
/Users/mcoblenz/code/Obsidian/src/main/scala/edu/cmu/cs/obsidian/typecheck/AstTransformer.scala
Warning:(356, 9) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
        t match {
/Users/mcoblenz/code/Obsidian/src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
Warning:(36, 13) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
            t match {
Warning:(468, 56) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
            val retTypeCalleePoV: UnpermissionedType = astType match {
Warning:(916, 21) match may not be exhaustive.
It would fail on the following input: InterfaceContractType(_, _)
                arg.typ match {

**Comment by broomweed** [comment]
I only have one more warning to deal with, so I'm guessing this won't take too much time. So, I'd say half a day at most.

**Comment by broomweed** [comment]
Fixed with #112.
