### ISSUE TITLE
Protobuf dependency for generated jars not working as expected

### ISSUE THREAD

**Issue by tyleretzel** [mcoblenz/Obsidian#12]
If you're trying to run the generated jars and getting "java.lang.NoClassDefFoundError", this is because the jar expects "protobuf-java-3.2.0.jar" to be in the same exact directory as the generated jar. For example, if we generate "obs_output/Simple.jar", there must exist "obs_output/protobuf-java-3.2.0.jar". I'll have to look into how to fix this. Ideally, we want protobuf to simply be in the class path when the jar is executed.

**Comment by sachi-sharma** [comment]
Fixed with #77
