### ISSUE TITLE
Misleading error message given when trying to initialize a field in a contract

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#125]
A parse error is given for the contract below due to the invalid initialization:

**To Reproduce**
Compile this:
````
contract Bad {
    int x = 3;
}
````

**Expected behavior**
Error message should indicate that assignments are only possible in transactions.

Actual behavior: parse error.

**Comment by broomweed** [comment]
PR #149 commit 11dce7b
