### ISSUE TITLE
Make a client that can generate HyperLedger-style requests

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#14]
See this page for the JSON format: http://hyperledger-fabric.readthedocs.io/en/stable/API/CoreAPI/

**Comment by YBthebest** [comment]
We can close this issue now, right? @mcoblenz

**Comment by mcoblenz** [comment]
Yes, this is done now.

**Comment by mcoblenz** [comment]
Though we never really attempted compatibility with general Hyperledger contracts. That might be worth considering in the future. For now, Obsidian clients talk to Obsidian smart contracts.
