### ISSUE TITLE
Better error message for arguments of wrong type

### ISSUE THREAD

**Issue by pkoronkevich** [mcoblenz/Obsidian#165]
If you pass a transaction an argument of the wrong type, it gives a subtyping error : "Expected type C@S2, given type C@S1", which isn't very intuitive because it doesn't mention the transaction.

**Comment by ReedOei** [comment]
@mcoblenz This may have been resolved; compiling:
```
main contract C {
    transaction f(int x) {
    }

    transaction g() {
        f(true);
    }
}
```

gives

```
TestWrongType.obs 13.9: Found type 'C@S2' as an argument to 'f', but the argument 'x' is expected something of type 'C@S1'.
```

which mentions the transaction name.
