### ISSUE TITLE
Give ownership of resources to caller

### ISSUE THREAD

**Issue by pkoronkevich** [mcoblenz/Obsidian#171]
**Describe the bug**
When owned resources appear as arguments to transaction, ownership should be given back to the caller, instead of getting an UnusedOwnership error when the argument is either not returned or transferred.

**To Reproduce**
```
main contract A {

    transaction t(B@S1 >> S2 b) {
        b.toS2();
    }
}


resource contract B {
    state S1;
    state S2;

    B@S1() {
        ->S1;
    }

    transaction toS2(B@S1 >> S2 this) {
        ->S2;
    }
}
```
Gives `At 5.5: Variable 'b' holds ownership, but is unused at the end of its scope.`

**Comment by mcoblenz** [comment]
This works now.
