### ISSUE TITLE
Generating code with the same constructors

### ISSUE THREAD

**Issue by pkoronkevich** [mcoblenz/Obsidian#172]
**Describe the bug**
When a contract is defined with multiple constructors that take the same arguments that aren't subtypes (i.e. a C@S1 vs C@S2), it passes the type checker but the constructors generated in Java take the same arguments.

**To Reproduce**
```
main contract A {

    transaction makeB() {
        B@Shared b = new B(new C());
    }
}

contract B {

    B@Shared(C@S1 s1c) {}
    B@Shared(C@S2 s2c) {}
}

contract C {
    state S1;
    state S2;

    C@S1() {
        ->S1;
    }
}
```
results in
`B.java:14: error: constructor B( C ) already defined in class B public B(C s2c) `

**Comment by ReedOei** [comment]
@mcoblenz It seems that statically dispatching is actually more difficult than anticipated. There's two main issues:

1. In the generated `init` method, we load the arguments from the archive, which I believe means we would at least need a dynamic state check there.

2. In "regular" calls to the constructor, such as inside transactions, we just use the Java constructor for the class, whose name we can't change. We could call the default constructor then call the `new_X` "constructors", but we don't save the types of the constructor arguments from the typechecking phase, so there's no way to know which constructor to call. 

I could modify the code to either save the type information or re-infer the types of the arguments, but it seems like this would be a more major change. On the other hand, I already have the if-statement dynamic dispatch version working from yesterday. 

What do you think is the best approach here?

**Comment by mcoblenz** [comment]
Okay, that makes sense. I guess the simple dynamic check is probably preferable for now if we can restrict it to the case where the constructors are overloaded in this way.
