### ISSUE TITLE
Typechecker should rule out assignment to transaction parameters 

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#191]
This is needed for soundness; otherwise a programmer might make the typechecker pass when the actual object is in the wrong state.

**Comment by ReedOei** [comment]
@mcoblenz This seems to have already been handled: for example, when compiling:
```
main contract C {
    C() {}

    transaction f(int x) {
        x = 2;
    }
}
```

I get:

```
5.11: Can't reassign to variables that are formal parameters or which are used in a dynamic state check.
```

**Comment by mcoblenz** [comment]
Oh good. Yes, I remember implementing that now.
