### ISSUE TITLE
Wrong type of the Client in Tutorial 

### ISSUE THREAD

**Issue by zyh1121** [mcoblenz/Obsidian#193]
@ https://github.com/mcoblenz/Obsidian/wiki/Obsidian-Tutorial

It seems `ExampleClient` in the 2nd line should be `Example@Shared`

```
main contract ExampleClient {
   transaction main(remote ExampleClient ex) {
      int oldX = ex.setX(42);
      ex.setX(2);
   }
}
```

Also, it would be helpful to mention the client code should include the following at the very beginning

`import <path to the server code>`

Thanks

**Comment by mcoblenz** [comment]
I've fixed this. Thanks!
