### ISSUE TITLE
Compiler doesn't know state after constructor

### ISSUE THREAD

**Issue by ReedOei** [mcoblenz/Obsidian#225]
In the following contract, the compiler doesn't seem to know what state an `X` is in after being created, but it seems like it should:

```
main contract X {
    state S1;
    state S2;

    X() {
        ->S1;
    }

    transaction f(X@S1 >> S2 this) {}

    transaction g() {
        X x = new X();
        x.f(); // error occurs here
    }
}
```

Compiling this gives:

```
test.obs 15.11: Cannot invoke f on a receiver of type X@Owned; a receiver of type X@S1 is required.
```

EDIT: It seems you can change the constructor to read `X@S1() { ... }` and it will work. Still, maybe there should be some warning for this. Or, perhaps, since the constructor must put the object into some state, the @S1 part should be required.

**Comment by mcoblenz** [comment]
Elsewhere, we require a permission on types, so I think probably we should require one on constructors too.
