### ISSUE TITLE
Support for compound assignment operators

### ISSUE THREAD

**Issue by ReedOei** [mcoblenz/Obsidian#237]
For example, it would be nice to be able to write `i += n` rather than `i = i + n`. Probably should support the major operations (`+`, `-`, `*`, `/`), but not sure anything else is worth supporting.

**Comment by mcoblenz** [comment]
There have been bugs in which people wrote "a =+b" instead of "a +=b". I suspect it is safer to not support += in order to prevent this kind of serious mistake.

**Comment by ReedOei** [comment]
Is that `a =+ b` meaning "a equals positive b"? If so, it seems that Obsidian doesn't support writing `+b` in any case (it gets rejected with `expression expected at ...`), so that particular problem wouldn't occur.

**Comment by mcoblenz** [comment]
Yes, but it does support unary -.
