### ISSUE TITLE
[feature request] font size options

### ISSUE THREAD

**Issue by omega3** [mcoblenz/Obsidian#296]
Sorry, but using css to create simple text notes is a big turn-off for normal, non-tech users. When I start to use any note taking app, I would like to focus on creating notes, not on searching the Internet for a way to change something so basic as font size.

Just create [options in configuration](https://forum.obsidian.md/uploads/default/original/2X/8/83f96718965f8f0acc2611694099af2818872c6f.png), as it is for example in Stroll, which also uses markdown

https://giffmex.org/stroll/stroll.html

**Comment by mcoblenz** [comment]
This is not the repository you're looking for. See this instead: https://obsidian.md/community
