### ISSUE TITLE
[feature request] markdown edit icons

### ISSUE THREAD

**Issue by omega3** [mcoblenz/Obsidian#297]
I would love to have simple [edit icons](https://forum.obsidian.md/uploads/default/original/2X/c/c68d969558abc19ccab93ede78ea5d8591d808ab.png) like in Stroll or Tiddlywiki:
Learning all these shortcuts to start simple editing is also a turn-off. Not that I can’t do that but come on - there are more pleasurable things in life. Even when I write this message there are editor icons available here and on Obsidian forum as well.

Software that is based on one of the greatest ideas of note taking should not turn off users just because from the start they need to learn tones of shortcuts and remember how to bold some text.

**Comment by mcoblenz** [comment]
This is a blockchain programming language, not note-taking software.
