### ISSUE TITLE
testing/execution infrastructure (due EOD 3/26)

### ISSUE THREAD

**Issue by ivoysey** [mcoblenz/Obsidian#304]
write a script to:
- [x] compile solidity to yul locally
- [x] execute yul locally on a ganache block chain via POST
- [x] ~execute yul running locally with inputs~
- [x] direct the result of running local yul code to stdout
- [x] ~Ensure that Travis CI succeeds.~
- [x] Submit PR that encompasses the above. You can make a new branch or you can use codegen for this.
- [x] ~fix op codes~
- [x] figure out why the identical POST isn't running on travis

(_struck through and checked off items have refactored to a different issue._)

**Comment by ivoysey** [comment]
- [ ] try rewriting this with web3 instead of curl to resolve the `400` and op codes problem.

with respect to bad op codes, one of three possibilities:

1. [60%] we're not following the protocol to interact with ganache-cli, even though it seems like we are, and bits are getting scrambled. differently on different machines -- sometimes a bad request, sometimes the request goes through but returns garbage
2. [30%] obsidian is producing bad output yul and instead of crashing or giving an error, `solc` produces bad things
3. [10%] `solc` is busted or has bitrotted and we'll need to file a bug report showing that there are op codes in the evm that are not permitted.

**Comment by ivoysey** [comment]
instead of rewriting this in web3, i paid off some techincal debt and got the script to produce the same output on travis and locally. it was a combination of zsh and bash not having the same semantics for quotation, it not being obvious that i was running the script locally in zsh, and some sloppy JSON objects.

**Comment by ivoysey** [comment]
this morning we determined that the infrastructure is not the problem, we are indeed generating yul that generates incorrect opcodes. in the interest of keeping tasks separate and clear, i'm going to make a new issue for fixing that and the discussion that entails. this issue should be taken care of by #301

**Comment by mcoblenz** [comment]
We should not consider issues closed until the corresponding PRs are merged.

**Comment by ivoysey** [comment]
since i have merged these changes into master, i'm now going to close this issue and move the corresponding card on the board.
