### ISSUE TITLE
fix opcodes (due 3/31)

### ISSUE THREAD

**Issue by ivoysey** [mcoblenz/Obsidian#309]
Obsidian produces Yul output for the empty contract that, when compiled by `solc`, does not produce valid opcodes. Specifically, on 
```
main contract EmptyContract {
}
```
we generate
```
object "EmptyContract" {
    code {
            mstore(64,128)
    }
    object "EmptyContract_deployed" {
        code {
            mstore(64,128)   
        }   
    }  
}
```
which ganache will not run. If I manually add `return` statements to produce the Yul file
```
object "EmptyContract" {
    code {
	mstore(64,128)
        return(0,0)
    }
    object "EmptyContract_deployed" {
        code {
             mstore(64,128)
             return(0,0)
        }
    }
}
```
then `solc` will compile this to something that ganache will run. it's not clear that `return` has the right semantics, although with those arguments it's probably close enough. `leave` is closer, but since there are no functions or transactions in the input contract (because it's the empty contract) we also produce Yul with no functions; leave must be called from inside a function. That is to say, manually producing the Yul
```
object "EmptyContract" {
    code {
	mstore(64,128)
        leave
    }
    object "EmptyContract_deployed" {
        code {
             mstore(64,128)
             leave
        }
    }
}
```
won't even compile:
```
workmode@bruce Desktop % docker run -v "$( pwd -P )":/sources ethereum/solc:stable --abi --bin --strict-assembly /sources/test.yul
Warning: Yul is still experimental. Please use the output with care.
Error: Keyword "leave" can only be used inside a function.
 --> /sources/test.yul:3:2:
  |
3 | 	leave
  | 	^^^^^
Error: Keyword "leave" can only be used inside a function.
 --> /sources/test.yul:7:7:
  |
7 | 	     leave
  | 	     ^^^^^
workmode@bruce Desktop %
```

**Comment by ivoysey** [comment]
For reference, at the time of writing, the nightly `solc` image takes the solidity program
```
contract empty {
}
```
to
```
object "empty_1" {
    code {
        mstore(64, 128)
        if callvalue() { revert(0, 0) }

        constructor_empty_1()

        codecopy(0, dataoffset("empty_1_deployed"), datasize("empty_1_deployed"))

        return(0, datasize("empty_1_deployed"))

        function constructor_empty_1() {

        }

    }
    object "empty_1_deployed" {
        code {
            mstore(64, 128)

            if iszero(lt(calldatasize(), 4))
            {
                let selector := shift_right_224_unsigned(calldataload(0))
                switch selector

                default {}
            }
            if iszero(calldatasize()) {  }
            revert(0, 0)

            function shift_right_224_unsigned(value) -> newValue {
                newValue :=

                shr(224, value)

            }

        }

    }

}

```
Ganache happily accepts this as input when compiled to the evm `608060405234156100105760006000fd5b61001861002a565b603d61002f600039603d6000f361002d565b5b565bfe6080604052600436101515601e576016600035602e565b80601b565b50505b3615156025575b60006000fd603c565b60008160e01c90505b919050565b`. I don't know right away what everything is doing and what's dead code or not.

For now, I'm going to target my solution of adding `return(0,0)` to what we currently generate instead. It's possible that this is technical debt and we'll have to learn more about it later.

**Comment by ivoysey** [comment]
As of https://github.com/mcoblenz/Obsidian/commit/9d5a33cc09c82c417f48d5bbc7f45cec18a9d120, code gen produces the desired code and ganache will run that code and not return the error about opcodes. So I'm going to close this issue.

We are actually out code to disk now for the empty contract that is mangled because of a problem in the mustache file (#310) but coincidentally happens to also produce evm that does not get an error when sent to ganache). Since that's a separate problem that will get solved in its own branch, I've broken it out into its own issue.

**Comment by mcoblenz** [comment]
As with the other issue: please leave issues open until the changes have been merged.

**Comment by ivoysey** [comment]
OK! I've reopened both for that reason. I closed them at the same time as I put them in the "done" column on the project board, which I believe *does* make sense to keep that view less cluttered. Things exist in a grey area for a little while when I don't plan to work on them any longer but they haven't been merged, and maybe having open issues in the "done" column is an OK way to notate that.

**Comment by mcoblenz** [comment]
I think it would be better to not consider the tasks closed, either. It’s okay to have tasks where all the items are checked off but which are not done, or we can add a separate “merge” checkbox.

**Comment by ivoysey** [comment]
Maybe we should add another column to the board, for issues that are done
but under review or in the process of being merged so not fully "put to
bed" yet?

**Comment by mcoblenz** [comment]
Sure, if you want to do that, that would make sense.

**Comment by ivoysey** [comment]
since i have merged these changes into master, i'm now going to close this issue and move the corresponding card on the board.
