### ISSUE TITLE
"&#13;" added when .obs file is compiled to .yul

### ISSUE THREAD

**Issue by jasonyih** [mcoblenz/Obsidian#351]
(Windows 10)
When I compile a .obs file into .yul using "obsidianc --yul [path to file.obs]", the line `&#13;` is added to the .yul file:
![image](https://user-images.githubusercontent.com/19953636/126003413-62cf372d-68ef-4169-84a5-6d4db1cdc277.png)
[YulFileWithErrors.txt](https://github.com/mcoblenz/Obsidian/files/6833196/YulFileWithErrors.txt)

When I try to compile this .yul file in the Remix IDE, it causes these errors:
![image](https://user-images.githubusercontent.com/19953636/126003705-ddce38b9-4e21-43fa-bdca-5ca6dfce1ff2.png)

When I remove all of the `&#13;` from the file, it can be compiled.
![image](https://user-images.githubusercontent.com/19953636/126007262-558b64f7-5fe7-435b-afe7-2316bad4c42a.png)
[YulFileFixed.txt](https://github.com/mcoblenz/Obsidian/files/6833201/YulFileFixed.txt)

**Comment by ivoysey** [comment]
@jasonyih Thanks for reporting this! Which file obsidian are you compiling to get this, or does it happen on any input?

**Comment by jasonyih** [comment]
It happens on any input, but this specific file was BoolLiteral.obs.

**Comment by ivoysey** [comment]
this is fixed in master by https://github.com/mcoblenz/Obsidian/pull/352
