### ISSUE TITLE
Forbid transaction arguments that shadow fields

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#44]
Otherwise we end up with confusing code and confusing error messages, such as:

`At 6.4: Found type 'shared C', but expected something of type 'int'`

for input:
````
main contract C { C() {->S({x=0, y=0}); } state S {
    int x;
    int y;
 }
 transaction t(C x) available in S
 { ->S({x = y, y = x}); }
}
````

**Comment by pkoronkevich** [comment]
PR #97 commit 0f202a44b45e9480164fddf01b4f1e39b8a1e6f2
