### ISSUE TITLE
Exception thrown parsing a program with unmatched curly brace

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#53]
The test below throws an exception trying to report the error message. Note the missing close curly brace at the end. We should report the error without throwing an uncaught exception.
```
    @Test def pathTests() = {
        shouldSucceed(
            """main contract UsesC {
              |    transaction t1() {
              |        int x = 2;
              |    }
              | 
            """.stripMargin)
```

**Comment by suzzglennon** [comment]
Tested - not actually an issue, the error is displayed correctly.
