### ISSUE TITLE
Allow "available in" and "returns" in any order

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#59]
Right now, in transaction declarations, "returns" must come before "available in"; this restriction is arbitrary and we should relax this constraint in the parser.

**Comment by suzzglennon** [comment]
Issue changed: now requiring "returns" first, followed by any number of available ins and ends in states in any order

**Comment by suzzglennon** [comment]
https://github.com/mcoblenz/Obsidian/pull/79
