### ISSUE TITLE
Add support for "ends in" guarantees on constructors

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#63]
Right now, I think the typechecker ignores these when inferring types of calls to constructors.

**Comment by mcoblenz** [comment]
Revised syntax:

Support this:
````
    C@S1() {
        ->S1;
    }
````

But give an error on extra constructors that have the same arguments, e.g. in the same file as the above code:
````
    // bogus
    C@S2() {
        ->S2;
    }
````

**Comment by pkoronkevich** [comment]
PR #139 commit 8e03fd1c151bb9f42faf2bbcf1ebf01584db14d7
