### ISSUE TITLE
Enable automated tests that run the whole compiler and run unit tests on compiled code

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#73]

**Comment by mcoblenz** [comment]
An intermediate step is to have unit tests that run the compiler on test cases and just makes sure that the output Java code actually builds with javac.

**Comment by sachi-sharma** [comment]
Added tests that run the compiler on test cases and makes sure that the output Java code actually builds.

Another prerequisite.  #84

**Comment by mcoblenz** [comment]
To summarize our whiteboard conversation, one way this could look is that we have a test specification format, "obstest", and a shell script "obstest" that executes test cases. Given:

TestFoo.obs  // blockchain contract
TestFooClient.obs // client implementation
TestFoo.obstest // test script

one could run:
```
> obstest TestFoo.obstest
```

The contents of TestFoo.obstest might be:
```
server: TestFoo.obs
client: TestFooClient.obs
42
```
When run, `obstest TestFoo.obstest` would execute the server, execute the client, wait for termination (up to N seconds), and compare the output to the expected output (in this case, 42). No output might mean test passed; output would specify expected and obtained results.

**Comment by mcoblenz** [comment]
Also, we should include running these scripts as part of CI.

**Comment by mcoblenz** [comment]
https://github.com/mcoblenz/Obsidian/pull/121

**Comment by broomweed** [comment]
This still needs to be integrated with CI.

**Comment by broomweed** [comment]
Integrated with CI as of #143.
