### ISSUE TITLE
Add support for typestate specifications in arguments

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#78]
For example:
```transaction close(File@Open >> Closed f)```
is a transaction that takes an open file and guarantees that it will close it.

If a transaction takes an argument that has a typestate specification but no change specification (no ">>") then it guarantees that when it exits, the object's typestate is the same as when the transaction begins.

**Comment by pkoronkevich** [comment]
PR #153 commit 93641556f5b4ee7f9f87c6a486c4432b25c96b02
